locatie = 'locatie'
title = 'title'
description = 'description'
description2 = 'description2'
description3 = 'description3'
item = 'item'
descriptionItems = 'descriptionItems'
descriptionItems2 = 'descriptionItems2'
lijst = 'lijst'
opties = 'opties'
gameOver = 'gameOver'
nodig = 'nodig'
N = 'n'
O = 'o'
Z = 'z'
W = 'w'

#LOCATIES
locatie = {
  "Bar": {
    title : "Bar",
    description : "Hier kan je een drankje doen, maar om de manager te helpen zal je toch echt eerst moeten gaan werken. (Tip: pak de bestelling en bekijk hem in je inventory!)",
    descriptionItems : '1',
    descriptionItems2 : '1',
    opties : "N: Gang\nO: Keuken\nZ: Ingang\nW: Garage",
    item : ['bestelling'],
    N: "Gang",
    O: "Keuken",
    Z: "Ingang",
    W: "Garage",
    gameOver : 'nee',
    nodig : '',
  }, 
  "Gang":{
    title : "Gang",
    description:"Je bent bij een kapstok. Handig, want je hebt nog al je waardevolle spullen in je jaszak zitten. Je hangt je jas op. Je ziet in je ooghoek een sleutel met het woord 'garage' erop staan. \nZo nu kan je aan het werk!",
    description2:"",
    description3:"",
    descriptionItems : '1',
    descriptionItems2 : '1',
    opties : "N: Keuken\nO: WC\nZ: Eetgedeelte\nW: Bar",
    item : ["sleutel"],
    N: "Keuken",
    O: "WC",
    Z: "Eetgedeelte",
    W: "Bar",
    gameOver : 'nee',
    nodig : '',
  },
  "Keuken" : {
    title: "Keuken",
    description: "Wat goed dat je er bent. We waren al aan het wachten op onze redder in nood. We wilden net champignonsoep maken, maar er is geen champignon meer in de voorraadkast van de keuken. Misschien ligt er ergens anders in het restaurant nog een voorraad aan voedsel?",
    description2: "Ah, fijn! Je hebt de champignons gevonden. Je snijdt ze snel in stukjes en doet ze in de pan en begint de soep te roeren. Na een paar minuten flink geroert te hebben, giet je de soep voorzichtig op de borden. De soep wordt meteen geserveerd en valt gelukkig goed in de smaak.",
    descriptionItems : 'champignons',
    descriptionItems2 : '1',
    opties: "N: Bar\nO: Gang\nZ: Garage",
    item : ['champignon taak'],
    N: "Bar",
    O: "Gang",
    Z: "Garage",
    W: "Keuken",
    gameOver : 'nee',
    nodig : '',
  },
  "Bijkeuken": {
    title : "Bijkeuken",
    description : "Wanneer je alle borden grondig hebt afgewassen komt de manager blij naar je toe met nog een taak voor jou vandaag. Je moet parasols op het buitenterras neerzetten (TIP: de parasols vindt je in de garage, verder is het ook handig de taak op te pakken; zo kun je overal je opdracht bekijken.)",
    descriptionItems : '1',
    descriptionItems2 : '1',
    opties : "N: Bar \nO: Keuken\nZ: Garage",
    item : ['glas', 'parasol taak'],
    N: "Bar",
    O: "Keuken",
    Z: "Garage",
    W: "Bijkeuken",
    gameOver : 'nee',
    nodig : '',
  },
  "Opslag": {
    title: "Opslag",
    description: "Hier is al het voorraad aan eten opgeslagen.",
    description2:"",
    description3:"",
    descriptionItems : '1',
    descriptionItems2 : '1',
    opties : "N: Bar\nO: Eetgedeelte \nZ: Keuken\nW: Achteringang",
    item : ['champignons'],
    N: "Bar",
    O: "Eetgedeelte",
    Z: "Keuken",
    W: "Achteringang",
    gameOver : 'nee',
    nodig : '',
  },
  "WC": {
    title : "WC",
    description: "Nou, je moet wel echt nodig... Even rustig op de wc met een boekje... Even je socials checken... Oeps, je bent de tijd vergeten... [game over]",
    descriptionItems : '1',
    descriptionItems2 : '1',
    gameOver: "ja",
  },
  "Ingang": {
    title: "Ingang",
    description: "Niet veel te zien hier..",description2:"Ik neem aan dat je parasols niet voor hier binnen wil gebruiken? Ze zijn toch echt voor buiten bedoeld.",
    descriptionItems : 'parasols',
    descriptionItems2 : '1',
    opties : "N: Gang\nO: Buitenterras\nZ: Opslag",
    item: [],
    N: "Gang",
    O: "Buitenterras",
    Z: "Opslag",
    W: "", 
    gameOver : 'nee',
    nodig : '',
  },
  "Achteringang" : {
    title: "Achteringang",
    description: "Je denkt dat je zo makkelijk stiekem weg kan gaan? Nou blijf dan maar weg. [GAME OVER]",
    descriptionItems : '1',
    descriptionItems2 : '1',
    gameOver : 'ja',
    nodig : '',
  },
  "Eetgedeelte": {
    title: "Eetgedeelte",
    description: "Oké, je hebt nog niet instructies gekregen, maar zo te zien zijn er obers nodig. Hoe moeilijk kan het nou zijn om mensen hun bestellingen op te nemen? ",
    description2:"Je hebt de bestelling gezien toch? Nou hup hup aan het werk. ",
    description3:"Dat heb je nou eens goed gedaan! De manager is trots.",
    descriptionItems: 'bestelling',
    descriptionItems2: 'glas water',
    opties : "N: Gang \nO: Keuken \nZ: Ingang\nW: Achteringang", 
    item: [] ,
    N: "Gang",
    O: "Keuken",
    Z: "Ingang",
    W: "Achteringang",
    gameOver : 'nee',
    nodig : '',
  },
  "Buitenterras": {
    title: "Buitenterras",
    description: "Je hebt de parasols nog niet? Je hebt ze wel eerst nodig als je ze wil gebruiken...",
    description2:"Wat ben je weer geweldig! Laat de parasols hier maar achter. Ontzettend bedankt!",
    descriptionItems : 'parasols',
    descriptionItems2 : '1',
    opties:"N: Garage\nZ: Ingang",
    item: [],
    N: "Garage",
    O: "Buienterras",
    Z: "Ingang",
    W: "Buitenterras",
    gameOver : 'nee',
    nodig : '',
  },
  "Garage": {
    title: "Garage",
    description: "Ah, mooi je hebt de garagesleutel, want zonder die sleutel kan je natuurlijk niet binnen. Nu kan je bij de berging waar de parasols voor het buitenterras liggen.",
    descriptionItems : '1',
    descriptionItems2 : '1',
    opties : "N: Buitenterras \nO: Ingang\nZ: Achteringang",
    item: ['parasols'],
    N: "Buitenterras",
    O: "Ingang",
    Z: "Achteringang",
    W: "",
    gameOver : 'nee',
    nodig : 'sleutel',
  },
}